tag: dev
use_mock_qserv: true

imagePullPolicy: Never
host: "minikube.lsst.codes"

secrets:
  enabled: false

vault_secrets:
  enabled: true
  path: 'secret/k8s_operator/minikube.lsst.codes/tap'

tap_schema_address: "tap-schema-db.tap-schema.svc.cluster.local"

gcs_bucket: 'async-results.lsst.codes'
gcs_bucket_url: 'http://async-results.lsst.codes'
