apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        env:
        - name: MYSQL_DATABASE
          value: "TAP_SCHEMA"
        - name: MYSQL_USER
          value: "TAP_SCHEMA"
        - name: MYSQL_PASSWORD
          value: "TAP_SCHEMA"
        - name: MYSQL_ROOT_HOST
          value: "%"
        image: lsstdax/mysql-db-demo
        ports:
        - containerPort: 3306
