apiVersion: apps/v1
kind: Deployment
metadata:
  name: tap-deployment
  labels:
    app: tap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tap 
  template:
    metadata:
      labels:
        app: tap
    spec:
      containers:
      - name: tap
        image: lsstdax/lsst-tap-demo:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: google-creds
          mountPath: "/etc/creds"
          readOnly: true
        env:
        - name: CATALINA_OPTS
          # Presto backend
          value: "-Dqservuser.jdbc.username=TAP_SCHEMA -Dqservuser.jdbc.password= -Dqservuser.jdbc.driverClassName=com.facebook.presto.jdbc.PrestoDriver -Dqservuser.jdbc.url=jdbc:presto://dax-presto:8080/tap_schema -Dtapuser.jdbc.username=TAP_SCHEMA -Domit-alma-test=true -Dtapuser.jdbc.password= -Dtapuser.jdbc.driverClassName=com.facebook.presto.jdbc.PrestoDriver -Dtapuser.jdbc.url=jdbc:presto://dax-presto:8080/tap_schema -Dca.nrc.cadc.reg.client.RegistryClient.local=true -Duws.jdbc.username=postgres -Duws.jdbc.driverClassName=org.postgresql.Driver -Duws.jdbc.url=jdbc:postgresql://postgresql-service/"
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/etc/creds/google_creds.json"
      volumes:
      - name: google-creds
        secret:
          secretName: google-creds
