apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-qserv-deployment
  labels:
    app: mock-qserv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mock-qserv
  template:
    metadata:
      labels:
        app: mock-qserv
    spec:
      containers:
      - name: mock-qserv
        image: lsstdax/mock-qserv:latest
        ports:
        - containerPort: 3306
