apiVersion: apps/v1
kind: Deployment
metadata:
  name: tap-schema-deployment
  labels:
    app: tap-schema
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tap-schema
  template:
    metadata:
      labels:
        app: tap-schema
    spec:
      containers:
      - name: tap-schema
        env:
        - name: MYSQL_DATABASE
          value: "TAP_SCHEMA"
        - name: MYSQL_USER
          value: "TAP_SCHEMA"
        - name: MYSQL_PASSWORD
          value: "TAP_SCHEMA"
        - name: MYSQL_ROOT_HOST
          value: "%"
        image: lsstdax/tap-schema-db:latest
        ports:
        - containerPort: 3306
