version: '3.2'
services:
  proxy:
    image: nginx:alpine
    ports:
      - '80:80'
    networks:
      - 'tap_obscore'
    volumes:
      - './proxy/default.conf:/etc/nginx/conf.d/default.conf'
    depends_on: 
      - 'tap_obscore'
  tap_obscore:
    build:
      dockerfile: Dockerfile
      context: ./
    depends_on:
      - 'tapdb'
    ports:
      - '8080:8080'
      - '5555:5555'
    networks:
      - 'tap_obscore'
    environment:
      CATALINA_OPTS: "-Dqservuser.jdbc.username=qsmaster -Dqservuser.jdbc.password= -Dqservuser.jdbc.driverClassName=com.mysql.cj.jdbc.Driver -Dqservuser.jdbc.url=jdbc:mysql://mock_qserv:3306/ -Dtapuser.jdbc.username=TAP_SCHEMA -Dtapuser.jdbc.password=TAP_SCHEMA -Dtapuser.jdbc.driverClassName=com.mysql.cj.jdbc.Driver -Dtapuser.jdbc.url=jdbc:mysql://tap_schema:3306/ -Dca.nrc.cadc.reg.client.RegistryClient.local=true -Duws.jdbc.username=postgres -Duws.jdbc.driverClassName=org.postgresql.Driver -Duws.jdbc.url=jdbc:postgresql://uwsdb/"
      GOOGLE_APPLICATION_CREDENTIALS: "/etc/google_creds.json"
    volumes:
      - './google_creds.json:/etc/google_creds.json'
  tapdb:
    image: opencadc/tap-oracle:11-xe
    shm_size: 1gb
    networks:
      - 'tap_obscore'
    volumes:
      - './sql:/docker-entrypoint-initdb.d/startup'
  uwsdb:
    image: library/postgres:11-rc1-alpine
    networks:
      - 'tap_obscore'
    volumes:
      - './uws-sql:/docker-entrypoint-initdb.d'
  tap_schema:
    image: mysql/mysql-server:8.0.13-1.1.8
    networks:
      - 'tap_obscore'
    environment:
      MYSQL_DATABASE: "TAP_SCHEMA"
      MYSQL_USER: "TAP_SCHEMA"
      MYSQL_PASSWORD: "TAP_SCHEMA"
      MYSQL_ROOT_HOST: "%"
    volumes:
      - './tap-schema:/docker-entrypoint-initdb.d/'
  mock_qserv:
    image: lsstdax/mock-qserv:latest
    networks:
      - 'tap_obscore'

networks:
  tap_obscore:
